name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3C:\Users\HP\Downloads\ToursandTravelsProject\Tour and Travel portal with admin panel\booking core\booking-core-ultimate-booking-system\booking-core-ultimate-booking-system\booking-core.2.3.0\booking-core.2.3.0\vendor\facade\ignition
      with:
        node-version: '16'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run:
        cd C:\Users\HP\Downloads\ToursandTravelsProject
        npm install

    - name: Run tests

      run:     
         cd C:\Users\HP\Downloads\ToursandTravelsProject
         npm test