name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run:
        cd "Tour and Travel portal with admin panel/booking core/booking-core-ultimate-booking-system/booking-core-ultimate-booking-system/booking-core.2.3.0/booking-core.2.3.0/vendor/facade/ignition" &&
        npm install

    - name: Run tests

      run:     
         cd "Tour and Travel portal with admin panel/booking core/booking-core-ultimate-booking-system/booking-core-ultimate-booking-system/booking-core.2.3.0/booking-core.2.3.0/vendor/facade/ignition" &&
         npm test