name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List directory contents at root
      run: ls -la

    - name: List directory contents in specified path
      run: ls -la "Tour and Travel portal with admin panel/booking core/booking-core-ultimate-booking-system/booking-core-ultimate-booking-system/booking-core.2.3.0/booking-core.2.3.0/vendor/facade/ignition"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: "Tour and Travel portal with admin panel/booking core/booking-core-ultimate-booking-system/booking-core-ultimate-booking-system/booking-core.2.3.0/booking-core.2.3.0/vendor/facade/ignition"

    - name: Run tests
      run: npm test
      working-directory: "Tour and Travel portal with admin panel/booking core/booking-core-ultimate-booking-system/booking-core-ultimate-booking-system/booking-core.2.3.0/booking-core.2.3.0/vendor/facade/ignition"
